# 1. Definimos el almacenamiento permanente (PVC)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-pvc
  namespace: supergiros
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
# 2. Definimos el Deployment conectado a ese almacenamiento
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqlserver
  namespace: supergiros
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sqlserver
  template:
    metadata:
      labels:
        app: sqlserver
    spec:
      containers:
      - name: sqlserver
        image: mcr.microsoft.com/mssql/server:2022-latest
        ports:
        - containerPort: 1433
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: MSSQL_PID
          valueFrom:
            configMapKeyRef:
              name: supergiros-config
              key: MSSQL_PID
        - name: SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: supergiros-secrets
              key: sa-password
        volumeMounts:
        - name: sqlserver-storage
          mountPath: /var/opt/mssql # Lugar donde SQL guarda los datos
      volumes:
      - name: sqlserver-storage
        persistentVolumeClaim:
          claimName: mssql-pvc # <-- AQUÍ CONECTAMOS LA PERSISTENCIA
---
# 3. Definimos el Servicio para que la API encuentre a la BD
apiVersion: v1
kind: Service
metadata:
  name: sqlserver
  namespace: supergiros
spec:
  selector:
    app: sqlserver
  ports:
  - port: 1433
    targetPort: 1433
  type: ClusterIP # Interno: Solo tu API dentro del clúster puede verla