// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SuperGiros.Transfer.Persistence.Contexts;

#nullable disable

namespace SuperGiros.Transfer.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SuperGiros.Transfer.Domain.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApellidoMaterno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApellidoPaterno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Celular")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastModifify")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModififyBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NroDocumento")
                        .HasColumnType("int");

                    b.Property<int>("State")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int>("TipoDocumento")
                        .HasColumnType("int");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApellidoMaterno = "Boza",
                            ApellidoPaterno = "Mollo",
                            Celular = "+51906081076",
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastModifify = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Arely",
                            NroDocumento = 70537513,
                            State = 1,
                            TipoDocumento = 0,
                            email = "arely@gmail.com"
                        },
                        new
                        {
                            Id = 2,
                            ApellidoMaterno = "Boza",
                            ApellidoPaterno = "Mollo",
                            Celular = "+51984452340",
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastModifify = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Luis",
                            NroDocumento = 60528515,
                            State = 1,
                            TipoDocumento = 1,
                            email = "luis@gmail.com"
                        },
                        new
                        {
                            Id = 3,
                            ApellidoMaterno = "Armejo",
                            ApellidoPaterno = "Huachaca",
                            Celular = "+51984173852",
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastModifify = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Maria",
                            NroDocumento = 85214785,
                            State = 1,
                            TipoDocumento = 0,
                            email = "maria@gmail.com"
                        },
                        new
                        {
                            Id = 4,
                            ApellidoMaterno = "Borda",
                            ApellidoPaterno = "Rojas",
                            Celular = "+51930161092",
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastModifify = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Javier",
                            NroDocumento = 85214787,
                            State = 1,
                            TipoDocumento = 1,
                            email = "javier@gmail.com"
                        },
                        new
                        {
                            Id = 5,
                            ApellidoMaterno = "Gallegos",
                            ApellidoPaterno = "Flores",
                            Celular = "+51901875421",
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastModifify = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Andre",
                            NroDocumento = 78541587,
                            State = 1,
                            TipoDocumento = 0,
                            email = "andre@gmail.com"
                        },
                        new
                        {
                            Id = 6,
                            ApellidoMaterno = "Bonifacio",
                            ApellidoPaterno = "Quispe",
                            Celular = "+51987951456",
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastModifify = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Alejandro",
                            NroDocumento = 78541588,
                            State = 1,
                            TipoDocumento = 1,
                            email = "alejandro@gmail.com"
                        },
                        new
                        {
                            Id = 7,
                            ApellidoMaterno = "Chumbe",
                            ApellidoPaterno = "Rojas",
                            Celular = "+51985741234",
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastModifify = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Martin",
                            NroDocumento = 78965895,
                            State = 1,
                            TipoDocumento = 0,
                            email = "martin@gmail.com"
                        });
                });

            modelBuilder.Entity("SuperGiros.Transfer.Domain.Entities.Offices", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<DateTime>("LastModifify")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModififyBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("MontoDiario")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("NumeroClientes")
                        .HasColumnType("int");

                    b.Property<decimal>("Saldo")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Offices", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "System",
                            Estado = 1,
                            LastModifify = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MontoDiario = 5000m,
                            Nombre = "Oficina Central",
                            NumeroClientes = 120,
                            Saldo = 20000m,
                            State = 1,
                            Ubicacion = "Lima - Centro"
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "System",
                            Estado = 1,
                            LastModifify = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MontoDiario = 3000m,
                            Nombre = "Oficina Norte",
                            NumeroClientes = 80,
                            Saldo = 15000m,
                            State = 1,
                            Ubicacion = "Lima - Los Olivos"
                        });
                });

            modelBuilder.Entity("SuperGiros.Transfer.Domain.Entities.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaRealizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastModifify")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModififyBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Moneda")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Sede")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("State")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int>("TipoMovimiento")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Transactions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountId = 1001,
                            Created = new DateTime(2026, 3, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "System",
                            Descripcion = "Depósito inicial de fondos",
                            FechaRealizacion = new DateTime(2026, 3, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastModifify = new DateTime(2026, 3, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Moneda = "Sol",
                            Monto = 1500.50m,
                            Sede = "Cusco",
                            State = 1,
                            TipoMovimiento = 1
                        },
                        new
                        {
                            Id = 2,
                            AccountId = 1001,
                            Created = new DateTime(2026, 3, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "System",
                            Descripcion = "Retiro a cuenta bancaria",
                            FechaRealizacion = new DateTime(2026, 3, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastModifify = new DateTime(2026, 3, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Moneda = "Sol",
                            Monto = 200.00m,
                            Sede = "Mazuko",
                            State = 1,
                            TipoMovimiento = 0
                        });
                });

            modelBuilder.Entity("SuperGiros.Transfer.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastModifify")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModififyBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2026, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "System",
                            LastModifify = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordHash = "$2a$11$iq30d.w1ZCDg2LU3VtpisuCG7kaLbFNE8nmiSLHZB5r3GSM3HpSBC",
                            Role = "Admin",
                            State = 1,
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(2026, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "System",
                            LastModifify = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordHash = "$2a$11$dfmFjF0uGcwaG5N/t9uzneSBeVA5cgCY6K1onyHqo5mHgUcXSrR2K",
                            Role = "Usuario",
                            State = 1,
                            Username = "usuario"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
